### ISSUE TITLE
Download button does not work

### ISSUE THREAD

**Issue by sdsznsk** [ArmaForces/Wiki#14]
https://wiki.armaforces.com/#/guides/missionmaking?id=_11-testy-na-serwerze

Download button "DO POBRANIA TUTAJ" in missionmaking section does not work and throws a 404.

It points to a wrong link URL:
https://wiki.armaforces.com/#/docs/_data/guides/missionmaking/MisjaTutorial.zip
it should be
https://wiki.armaforces.com/_data/guides/missionmaking/MisjaTutorial.zip

**Comment by N4ki** [comment]
An issue related to lack of proper forward slash in the path. Should be fixed by this PR #16
